### ISSUE TITLE
Zeo++ cif-parser fails on several cif-formats

### ISSUE THREAD

**Issue by mpougin** [yakutovicha/aiida-lsmo#71]
The cif-parser of Zeo++ chokes on many cif formats, inter alia the cifs created by aiida-autocreation.
At the moment, I convert every cif manually before I can submit it to the workchain.
@danieleongari @ltalirz can the "manage_crystal" conversion of the cifs be automated as part of the respective workflows?

**Comment by mpougin** [comment]
I think I can close this now as it's solved directly in Zeo++?

**Comment by ltalirz** [comment]
just to mention: some issues were fixed in zeopp-lsmo v0.4.2 but the zeo++ cif parser is homegrown and will never be perfect.

in case we keep running into issues, it would be very straightforward to add a `normalize_cif` calcfunction to the zeo++ plugin that calls `manage_crystal` under the hood and can be used on demand.
